# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  autoVolumeSrc = {
    pname = "autoVolumeSrc";
    version = "d7f7962724b567a8409ef2898602f2c57abddf5a";
    src = fetchgit {
      url = "https://github.com/amanharwara/spicetify-autoVolume";
      rev = "d7f7962724b567a8409ef2898602f2c57abddf5a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WquDmeaj+7M8DzGuHYOJgF6ifcs3vj3gIciZMaRQ3t4=";
    };
    date = "2020-02-16";
  };
  bloomSrc = {
    pname = "bloomSrc";
    version = "08267f1e77a89ddf6b9f5dee03607767aea49cac";
    src = fetchgit {
      url = "https://github.com/nimsandu/spicetify-bloom";
      rev = "08267f1e77a89ddf6b9f5dee03607767aea49cac";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-l2SfYgxqpQEnB0j+bcIoDzS9k2OKHjHJ85HD4sHsTvM=";
    };
    date = "2023-05-18";
  };
  catppuccinSrc = {
    pname = "catppuccinSrc";
    version = "fb7ef5a8d7b66d40e916e86d3ffb3b00d404ac76";
    src = fetchgit {
      url = "https://github.com/catppuccin/spicetify";
      rev = "fb7ef5a8d7b66d40e916e86d3ffb3b00d404ac76";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-yitiDqXZgX5NQlX66FW4YgS5fO2eF1W0QX5rKLD9uRE=";
    };
    date = "2023-05-10";
  };
  charlieS1103Src = {
    pname = "charlieS1103Src";
    version = "b5c82418f2893cab4cd7d0226844edb5e46f5847";
    src = fetchgit {
      url = "https://github.com/CharlieS1103/spicetify-extensions";
      rev = "b5c82418f2893cab4cd7d0226844edb5e46f5847";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Fl/nOgOqYwAVjVZGzxSEpkltODzTiB2TCkNZSgXyT5w=";
    };
    date = "2023-05-07";
  };
  comfySrc = {
    pname = "comfySrc";
    version = "74a5f5e4f1a4a02a60bc054cfc87884a4f6c0f16";
    src = fetchgit {
      url = "https://github.com/Comfy-Themes/Spicetify";
      rev = "74a5f5e4f1a4a02a60bc054cfc87884a4f6c0f16";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ryb7ndCCX9d+R1288Lf5itVMbu7Agp35VJ2dcytyu2U=";
    };
    date = "2023-05-13";
  };
  customAppsExtensionsSrc = {
    pname = "customAppsExtensionsSrc";
    version = "0f5e79fe43abf57f714d7d00bd288870d5b6f718";
    src = fetchgit {
      url = "https://github.com/3raxton/spicetify-custom-apps-and-extensions";
      rev = "0f5e79fe43abf57f714d7d00bd288870d5b6f718";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-4zL/z8dCafy5V95ASR3c6TffMh9wdpnclAjddD9TX84=";
    };
    date = "2022-05-02";
  };
  dakshExtensions = {
    pname = "dakshExtensions";
    version = "10df647472e90bb01a28ac34d38034ff534639e3";
    src = fetchgit {
      url = "https://github.com/daksh2k/Spicetify-stuff";
      rev = "10df647472e90bb01a28ac34d38034ff534639e3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-9xTmP8fD3au7NTQb5bog73hv4XXOrKMXHYzWIo+13Q0=";
    };
    date = "2023-04-29";
  };
  defaultDynamicSrc = {
    pname = "defaultDynamicSrc";
    version = "c9b70479a5445c09fadb575d2d5cf940b871ff4d";
    src = fetchgit {
      url = "https://github.com/JulienMaille/spicetify-dynamic-theme";
      rev = "c9b70479a5445c09fadb575d2d5cf940b871ff4d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-cj6Se4lJFTg1j+4vclnfp1qWF5FkHzBZqUldrj70Akw=";
    };
    date = "2022-09-17";
  };
  draculaSrc = {
    pname = "draculaSrc";
    version = "97bf149e7afbe408509862591a57f1d8e2dfc5d7";
    src = fetchgit {
      url = "https://github.com/Darkempire78/Dracula-Spicetify";
      rev = "97bf149e7afbe408509862591a57f1d8e2dfc5d7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IS0A/5zTZou9yQJ0zpqAwiW2COt/TGoscN99WGFR9FA=";
    };
    date = "2022-02-14";
  };
  fluentSrc = {
    pname = "fluentSrc";
    version = "772cd8491105d679c7d3d1ff3f927b4a3dbb0e62";
    src = fetchgit {
      url = "https://github.com/williamckha/spicetify-fluent";
      rev = "772cd8491105d679c7d3d1ff3f927b4a3dbb0e62";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IrSIW0tVLvu9k2QMzkT8yFhmghOhIT7PfdTie8D7tL8=";
    };
    date = "2022-12-11";
  };
  genreSrc = {
    pname = "genreSrc";
    version = "f2cb950a7e27cce3bfd4168141b5c5e55552df5a";
    src = fetchgit {
      url = "https://github.com/Shinyhero36/Spicetify-Genre";
      rev = "f2cb950a7e27cce3bfd4168141b5c5e55552df5a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-R7D6oiSZviZQiMo6GSe4phQKfUmLNToXkyv6F4JXf3M=";
    };
    date = "2023-03-04";
  };
  groupSessionSrc = {
    pname = "groupSessionSrc";
    version = "a9fa45da69495137b2f7272f61ff8d1a457aef5b";
    src = fetchgit {
      url = "https://github.com/timll/spotify-group-session";
      rev = "a9fa45da69495137b2f7272f61ff8d1a457aef5b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-YTbnNLzPc0iMJZfH3QwSEX/gpAqIlchmbsULjM8musA=";
    };
    date = "2022-09-15";
  };
  hidePodcastsSrc = {
    pname = "hidePodcastsSrc";
    version = "8bb29909cbce6aa642e3b42841ef2f79b344ca72";
    src = fetchgit {
      url = "https://github.com/theRealPadster/spicetify-hide-podcasts";
      rev = "8bb29909cbce6aa642e3b42841ef2f79b344ca72";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-L5zTpj8X3KC4sKyZEtBHzE8l/N23uEM6zqd7KzPhrlc=";
    };
    date = "2023-05-09";
  };
  historySrc = {
    pname = "historySrc";
    version = "577e34f364127f18d917d2fe2e8c8f2a1af9f6ae";
    src = fetchgit {
      url = "https://github.com/einzigartigerName/spicetify-history";
      rev = "577e34f364127f18d917d2fe2e8c8f2a1af9f6ae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ORG1oNvMTJxrI3spfAuN+pCKTKvQfhqUIYT9NM1yZTs=";
    };
    date = "2021-05-20";
  };
  huhExtensionsSrc = {
    pname = "huhExtensionsSrc";
    version = "8cca264223e99e9f416182c00ccd182746a18ac6";
    src = fetchgit {
      url = "https://github.com/huhridge/huh-spicetify-extensions";
      rev = "8cca264223e99e9f416182c00ccd182746a18ac6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6tX4z5TzFKLGQmPXyBz2sns0YgIkBCt3pMn0jSWTGCA=";
    };
    date = "2023-01-29";
  };
  lastfmSrc = {
    pname = "lastfmSrc";
    version = "d2f1d3c1e286d789ddfa002f162405782d822c55";
    src = fetchgit {
      url = "https://github.com/LucasBares/spicetify-last-fm";
      rev = "d2f1d3c1e286d789ddfa002f162405782d822c55";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/C4Y3zuSAEwhMXCRG2/4b5oWfGz/ij6wu0B+CpuJKXs=";
    };
    date = "2022-11-20";
  };
  localFilesSrc = {
    pname = "localFilesSrc";
    version = "1bfd2fc80385b21ed6dd207b00a371065e53042e";
    src = fetchgit {
      url = "https://github.com/hroland/spicetify-show-local-files";
      rev = "1bfd2fc80385b21ed6dd207b00a371065e53042e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-neKR2WaZ1K10dZZ0nAKJJEHNS56o8vCpYpi+ZJYJ/gU=";
    };
    date = "2022-04-12";
  };
  marketplaceSrc = {
    pname = "marketplaceSrc";
    version = "7a0637484ffd007f74a04d2e6388c8fbd7557e63";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-marketplace";
      rev = "7a0637484ffd007f74a04d2e6388c8fbd7557e63";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-DP9EnqDh9jwy7G8pALL+V9Xm2Yyt8yUPJVS4OtZqu9Q=";
    };
    date = "2023-05-17";
  };
  nameThatTuneSrc = {
    pname = "nameThatTuneSrc";
    version = "143007515cc2476c82dc9ccf7bc0213b2c6a3d1e";
    src = fetchgit {
      url = "https://github.com/theRealPadster/name-that-tune";
      rev = "143007515cc2476c82dc9ccf7bc0213b2c6a3d1e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-QdaOpBNNy6bGxlvh9WyouO/9cTljYfac7e6mZfeLJms=";
    };
    date = "2023-04-11";
  };
  nordSrc = {
    pname = "nordSrc";
    version = "57d135e5ec10bee1e4e67d72f56718a3c075a53c";
    src = fetchgit {
      url = "https://github.com/Tetrax-10/Nord-Spotify";
      rev = "57d135e5ec10bee1e4e67d72f56718a3c075a53c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-95ZcijR+DOX3xQlCstOdGisBwOenC6muojdpNfDKneM=";
    };
    date = "2023-05-18";
  };
  officialSrc = {
    pname = "officialSrc";
    version = "577bb1257d1b692578d5e6cd20a99a5ee864897a";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-cli";
      rev = "577bb1257d1b692578d5e6cd20a99a5ee864897a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-KhGPn3rtfWDM0Axd36b5qqSgIBvCVxqhQOPHaEROzJI=";
    };
    date = "2023-05-18";
  };
  officialThemes = {
    pname = "officialThemes";
    version = "e945db43cb51e8036a4b3412540eb18182618d2c";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-themes";
      rev = "e945db43cb51e8036a4b3412540eb18182618d2c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-1ZmavROvKdC2234wZwb2mY0ZwYMwxlPAJK9Tj4kUQ+A=";
    };
    date = "2023-05-05";
  };
  omniSrc = {
    pname = "omniSrc";
    version = "253ae45d2cac2dc3d92a43193ea8f6d9e7e1d3aa";
    src = fetchgit {
      url = "https://github.com/getomni/spicetify";
      rev = "253ae45d2cac2dc3d92a43193ea8f6d9e7e1d3aa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-5II+4096fOcCA7J4XZfIHSse+3/YJ+EY5KW3GXl+dn8=";
    };
    date = "2023-01-20";
  };
  orchisSrc = {
    pname = "orchisSrc";
    version = "5bf3fcf0696514dcf3e95f4ae3fd00261ccc5dcc";
    src = fetchgit {
      url = "https://github.com/canbeardig/Spicetify-Orchis-Colours-v2";
      rev = "5bf3fcf0696514dcf3e95f4ae3fd00261ccc5dcc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-9cU2Wlg5W57JpBfzIOXvpRYI8Q3CsH+UsdjQseTr9bs=";
    };
    date = "2022-05-20";
  };
  playlistIconsSrc = {
    pname = "playlistIconsSrc";
    version = "4e2fdda5079b441eca8d4d9f7479db82f6cc20b8";
    src = fetchgit {
      url = "https://github.com/jeroentvb/spicetify-playlist-icons";
      rev = "4e2fdda5079b441eca8d4d9f7479db82f6cc20b8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ocDsR4+AAfycWcs1H3JV1h7WgIONlu3BQ148cnAMOPI=";
    };
    date = "2023-03-31";
  };
  powerBarSrc = {
    pname = "powerBarSrc";
    version = "3b7e0559e91e76975cca41bafdb4ea2990dd468a";
    src = fetchgit {
      url = "https://github.com/jeroentvb/spicetify-power-bar";
      rev = "3b7e0559e91e76975cca41bafdb4ea2990dd468a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-4sZnfnwwhMSrwbS1tFV6bUlifz9g4MUl0fDlZDzolRU=";
    };
    date = "2023-05-04";
  };
  retroBlurSrc = {
    pname = "retroBlurSrc";
    version = "d5b815b4139d97844190984a89ea8ab4eb42529c";
    src = fetchgit {
      url = "https://github.com/Motschen/Retroblur";
      rev = "d5b815b4139d97844190984a89ea8ab4eb42529c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-nfxN9bGB67YFumHjnmKE7u/zrJ8EMxDYKwOUOspGcNE=";
    };
    date = "2023-05-15";
  };
  spotifyCanvasSrc = {
    pname = "spotifyCanvasSrc";
    version = "ee7a441503e9fb763be81d868d9e1dd8d748a924";
    src = fetchgit {
      url = "https://github.com/itsmeow/Spicetify-Canvas";
      rev = "ee7a441503e9fb763be81d868d9e1dd8d748a924";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-OKovKLBwsiNWo3rux5waDefI5qFu2pou21WmRsN4h4Y=";
    };
    date = "2023-05-11";
  };
  spotifyNoPremiumSrc = {
    pname = "spotifyNoPremiumSrc";
    version = "f6efff59ee7ecf25ebdf4efba4b3ffdcdd8d5b45";
    src = fetchgit {
      url = "https://github.com/Daksh777/SpotifyNoPremium";
      rev = "f6efff59ee7ecf25ebdf4efba4b3ffdcdd8d5b45";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-8Ic410OYURUCnZ+ke+/MI2WHnt7peIWe2czomWmodZM=";
    };
    date = "2023-04-16";
  };
  spotifywmSrc = {
    pname = "spotifywmSrc";
    version = "8624f539549973c124ed18753881045968881745";
    src = fetchgit {
      url = "https://github.com/dasJ/spotifywm";
      rev = "8624f539549973c124ed18753881045968881745";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-AsXqcoqUXUFxTG+G+31lm45gjP6qGohEnUSUtKypew0=";
    };
    date = "2022-10-25";
  };
  startPageSrc = {
    pname = "startPageSrc";
    version = "d8764bcf7c5009318b489a66491c1b15e5d8bdf7";
    src = fetchgit {
      url = "https://github.com/Resxt/startup-page";
      rev = "d8764bcf7c5009318b489a66491c1b15e5d8bdf7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-mA+S5f1tZ+/K4G+iKm/9Ze7rCmLXhhOwUfwM/WsdDHs=";
    };
    date = "2023-04-16";
  };
  tetraxSrc = {
    pname = "tetraxSrc";
    version = "bea1698eaa5a8ce32572452cc1c6b9fc6a9d39de";
    src = fetchgit {
      url = "https://github.com/Tetrax-10/Spicetify-Extensions";
      rev = "bea1698eaa5a8ce32572452cc1c6b9fc6a9d39de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-O1yueXldU862Efh1T5ZonjZ2Y5triv60eJgCqeAaBSc=";
    };
    date = "2023-03-27";
  };
}
